### ISSUE TITLE
docker部署后一直运行不了，报错

### ISSUE THREAD

**Issue by louphier** [239144498/Streaming-Media-Server-Pro#18]
docker本地部署，mysql、redis，部署有段时间开始可以看的，最近一直报错。
2022-10-05 14:08:45.496 | INFO     | app.settings:<module>:14 - 配置加载中...
2022-10-05 14:08:46.245 | INFO     | app.settings:<module>:112 - 配置加载完成
2022-10-05 14:08:46.501 | INFO     | app.modules.DBtools:<module>:13 - 检测redis连接
2022-10-05 14:08:46.503 | INFO     | app.modules.DBtools:<module>:24 - redis已连接
2022-10-05 14:08:46.503 | INFO     | app.modules.DBtools:__init__:38 - 检测mysql连接
Traceback (most recent call last):
  File "/usr/local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 408, in main
    run(
  File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 576, in run
    server.run()
  File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/usr/local/lib/python3.9/site-packages/uvicorn/config.py", line 479, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/code/./app/main.py", line 9, in <module>
    from app.routers import app
  File "/code/./app/routers.py", line 12, in <module>
    from app.modules.DBtools import DBconnect
  File "/code/./app/modules/DBtools.py", line 81, in <module>
    DBconnect = DB()
  File "/code/./app/modules/DBtools.py", line 40, in __init__
    self.mysql = get_mysql_conn()
  File "/code/./app/modules/dbMysql.py", line 120, in get_mysql_conn
    return MySQLConnect(cursorclass, mysql_config)
  File "/code/./app/modules/dbMysql.py", line 18, in __init__
    self.connection = pymysql.connect(
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 353, in __init__
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 633, in connect
    self._request_authentication()
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 932, in _request_authentication
    auth_packet = _auth.caching_sha2_password_auth(self, auth_packet)
  File "/usr/local/lib/python3.9/site-packages/pymysql/_auth.py", line 265, in caching_sha2_password_auth
    data = sha2_rsa_encrypt(conn.password, conn.salt, conn.server_public_key)
  File "/usr/local/lib/python3.9/site-packages/pymysql/_auth.py", line 143, in sha2_rsa_encrypt
    raise RuntimeError(
RuntimeError: 'cryptography' package is required for sha256_password or caching_sha2_password auth methods

**Comment by kfcx** [comment]
> 

需要安装python模块，执行命令pip install cryptography

**Comment by louphier** [comment]
感谢回复，我是用的dockerhub的镜像，还需要在再安装python模块么。刚刚主机安装了cryptography，docker还是不能运行，报同意的错误。

**Comment by kfcx** [comment]
> 感谢回复，我是用的dockerhub的镜像，还需要在再安装python模块么。刚刚主机安装了cryptography，docker还是不能运行，报同意的错误。

模块需要装在容器中,你在配置文件中把defaultdb 留空再运行试试

**Comment by louphier** [comment]
defaultdb 留空运行后，再pip install cryptography，再用回mysql就可以了，谢谢！

**Comment by redrainl** [comment]
我docker部署的，没有连接数据库，昨天还可以正常用，今天发现日志报错。重拉了最新镜像，重启dockre，现象依旧，请求epg.xml和program.m3u正常，但channel.m3u8请求后报错，日志如下：

2022-10-06 14:23:42.079 | INFO     | app.settings:<module>:14 - 配置加载中...
2022-10-06 14:23:43.367 | INFO     | app.settings:<module>:90 - 配置加载完成
2022-10-06 14:23:43.860 | INFO     | app.modules.DBtools:<module>:13 - 检测redis连接
2022-10-06 14:23:43.874 | WARNING  | app.modules.DBtools:<module>:28 - redis连接失败
2022-10-06 14:23:43.875 | WARNING  | app.modules.DBtools:__init__:53 - 数据库连接失败
2022-10-06 14:23:44.738 | SUCCESS  | app.utile:__init__:48 - init final
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
**INFO:     101.88.146.xxx:43783 - "GET /program.m3u HTTP/1.1" 200 OK
INFO:     101.88.146.xxx:42368 - "GET /EPG.xml HTTP/1.1" 200 OK
INFO:     101.88.146.xxx:43799 - "GET /channel.m3u8?fid=4gtv-live006&hd=1080 HTTP/1.1" 200 OK**
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 68, in app
    await response(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/responses.py", line 260, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "/usr/local/lib/python3.9/site-packages/starlette/responses.py", line 256, in wrap
    await func()
  File "/usr/local/lib/python3.9/site-packages/starlette/responses.py", line 245, in stream_response
    async for chunk in self.body_iterator:
  File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 63, in iterate_in_threadpool
    yield await anyio.to_thread.run_sync(_next, iterator)
  File "/usr/local/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 53, in _next
    return next(iterator)
  File "/code/./app/utile.py", line 118, in generatem3u8
    self.check(fid, hd)
  File "/code/./app/utile.py", line 89, in check
    self.updateonline(fid, hd)
  File "/code/./app/utile.py", line 52, in updateonline
    last = int(re.findall(r"expires.=(\d+)", url).pop())
IndexError: pop from empty list
INFO:     101.88.146.134:43800 - "GET /channel.m3u8?fid=4gtv-live006&hd=1080 HTTP/1.1" 200 OK
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 68, in app
    await response(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/responses.py", line 260, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "/usr/local/lib/python3.9/site-packages/starlette/responses.py", line 256, in wrap
    await func()
  File "/usr/local/lib/python3.9/site-packages/starlette/responses.py", line 245, in stream_response
    async for chunk in self.body_iterator:
  File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 63, in iterate_in_threadpool
    yield await anyio.to_thread.run_sync(_next, iterator)
  File "/usr/local/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 53, in _next
    return next(iterator)
  File "/code/./app/utile.py", line 118, in generatem3u8
    self.check(fid, hd)
  File "/code/./app/utile.py", line 89, in check
    self.updateonline(fid, hd)
  File "/code/./app/utile.py", line 52, in updateonline
    last = int(re.findall(r"expires.=(\d+)", url).pop())
IndexError: pop from empty list

**Comment by kfcx** [comment]
> 

官方把台湾服务器ip拉黑了，现在有些频道不能看，你可以看看其他频道，我正在找解决办法。

**Comment by kfcx** [comment]
> defaultdb 留空运行后，再pip install cryptography，再用回mysql就可以了，谢谢！

不客气(*^_^*)
