### ISSUE TITLE
报错帮忙看看（解决了，原来是因为服务器没安置MySQL)

### ISSUE THREAD

**Issue by yifang5775** [239144498/Streaming-Media-Server-Pro#21]
root@DS3617xs:/Streaming-Media-Server-Pro# python3.10 main.py
2022-11-04 04:00:27.038 | INFO     | app.conf.config:<module>:58 - 配置加载中...
.Traceback (most recent call last):
  File "/volume2/@appstore/python310/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/volume2/@appstore/python310/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/volume2/@appstore/python310/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/volume2/@appstore/python310/lib/python3.10/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/volume2/@appstore/python310/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/volume2/@appstore/python310/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/volume2/@appstore/python310/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/volume2/@appstore/python310/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/volume2/@appstore/python310/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/volume2/@appstore/python310/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/volume2/@appstore/python310/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/volume2/@appstore/python310/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /382420058/owner/main/data (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Streaming-Media-Server-Pro/main.py", line 7, in <module>
    from app.api import app
  File "/Streaming-Media-Server-Pro/app/api/__init__.py", line 16, in <module>
    from app.conf import config
  File "/Streaming-Media-Server-Pro/app/conf/__init__.py", line 5, in <module>
    from .config import config
  File "/Streaming-Media-Server-Pro/app/conf/config.py", line 113, in <module>
    idata = eval(request.get("https://raw.githubusercontent.com/382420058/owner/main/data",
  File "/volume2/@appstore/python310/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/volume2/@appstore/python310/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/volume2/@appstore/python310/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/volume2/@appstore/python310/lib/python3.10/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /382420058/owner/main/data (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))

**Comment by yifang5775** [comment]
我是在群晖部署的

**Comment by kfcx** [comment]
问题解决了的话，那我这边关闭了
