### ISSUE TITLE
今天突然無法使用～附上BUG 是否解析出問題了？ 連docker也是一樣 有重新pull過了

### ISSUE THREAD

**Issue by charles0568** [239144498/Streaming-Media-Server-Pro#38]
DEBUG     2022-12-04 16:34:36.744 - app.api:init_app - 日志系统已加载
INFO:     Started server process [1080]
INFO:     Waiting for application startup.
INFO      2022-12-04 16:34:36.815 - app.api:startup - 已开启定时任务
C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\apscheduler\util.py:436: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return tzinfo.localize(dt)
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
INFO:     192.168.1.1:59484 - "GET /channel.m3u8?fid=4gtv-4gtv001&hd=1080 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\sentry_sdk\integrations\starlette.py", line 325, in _sentry_patched_asgi_app
    return await middleware(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\sentry_sdk\integrations\asgi.py", line 139, in _run_asgi3
    return await self._run_app(scope, lambda: self.app(scope, receive, send))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\sentry_sdk\integrations\asgi.py", line 188, in _run_app
    raise exc from None
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\sentry_sdk\integrations\asgi.py", line 183, in _run_app
    return await callback()
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\sentry_sdk\integrations\starlette.py", line 130, in _create_span_call
    return await old_call(app, scope, new_receive, new_send, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\sentry_sdk\integrations\starlette.py", line 223, in _sentry_exceptionmiddleware_call
    await old_call(self, scope, receive, send)
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\sentry_sdk\integrations\starlette.py", line 130, in _create_span_call
    return await old_call(app, scope, new_receive, new_send, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\sentry_sdk\integrations\starlette.py", line 130, in _create_span_call
    return await old_call(app, scope, new_receive, new_send, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\sentry_sdk\integrations\fastapi.py", line 106, in _sentry_app
    return await old_app(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 235, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\temp\Streaming-Media-Server-Pro\app\api\v2\endpoints\sgtv.py", line 67, in channel1
    code = get.check(fid)  # 檢查是否出错
           ^^^^^^^^^^^^^^
  File "C:\temp\Streaming-Media-Server-Pro\app\plugins\a4gtv\utile.py", line 108, in check
    code = self.updateonline(fid)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\temp\Streaming-Media-Server-Pro\app\plugins\a4gtv\utile.py", line 47, in updateonline
    status_code, a6, a12, a1, msg = get4gtvurl(fid)
                                    ^^^^^^^^^^^^^^^
  File "C:\temp\Streaming-Media-Server-Pro\app\plugins\a4gtv\endecrypt.py", line 24, in get4gtvurl
    with request.post(url=url, headers=header, data=data, allow_redirects=True) as res:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\temp\Streaming-Media-Server-Pro\app\common\request.py", line 39, in post
    return self.request.post(url, data=data, json=json, headers=headers, proxies=self.proxies, timeout=10, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.naihe.me', port=443): Read timed out. (read timeout=10)
INFO:     192.168.1.1:59490 - "GET /channel.m3u8?fid=4gtv-4gtv004&hd=1080 HTTP/1.1" 500 Internal Server Error

**Comment by kfcx** [comment]
已修复，重启服务解决
