### ISSUE TITLE
用docker 會出現 该ip已被程序拉黑，无法访问 解封禁规则https://github.com/239144498/Streaming-Media-Server-Pro/issues/

### ISSUE THREAD

**Issue by charles0568** [239144498/Streaming-Media-Server-Pro#39]
SystemExit: -1
[1mINFO    [0m  [32m2022-12-05 13:50:46.090[0m - [36msentry_sdk.integrations.logging[0m:[36msentry_patched_callhandlers[0m - [1m5.180.44.141:38606 - "GET /channel.m3u8?fid=4gtv-4gtv070 HTTP/1.1" 500[0m
[32m[1mSUCCESS [0m  [32m2022-12-05 13:50:50.548[0m - [36mapp.plugins.a4gtv.endecrypt[0m:[36mget4gtvurl[0m - [32m[1m4gtv-live050 216[0m
[31m[1mERROR   [0m  [32m2022-12-05 13:50:50.548[0m - [36mapp.plugins.a4gtv.utile[0m:[36mupdateonline[0m - [31m[1m该ip已被程序拉黑，无法访问[0m
[31m[1mERROR   [0m  [32m2022-12-05 13:50:50.549[0m - [36mapp.plugins.a4gtv.utile[0m:[36mupdateonline[0m - [31m[1m了解封禁规则https://github.com/239144498/Streaming-Media-Server-Pro/issues/14[0m
[31mERROR[0m:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/starlette.py", line 325, in _sentry_patched_asgi_app
    return await middleware(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/asgi.py", line 139, in _run_asgi3
    return await self._run_app(scope, lambda: self.app(scope, receive, send))
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/asgi.py", line 183, in _run_app
    return await callback()
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/starlette.py", line 130, in _create_span_call
    return await old_call(app, scope, new_receive, new_send, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/starlette.py", line 223, in _sentry_exceptionmiddleware_call
    await old_call(self, scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/starlette.py", line 130, in _create_span_call
    return await old_call(app, scope, new_receive, new_send, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/starlette.py", line 130, in _create_span_call
    return await old_call(app, scope, new_receive, new_send, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/fastapi.py", line 107, in _sentry_app
    return await old_app(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "/code/./app/api/v2/endpoints/sgtv.py", line 67, in channel1
    code = get.check(fid)  # 檢查是否出错
  File "/code/./app/plugins/a4gtv/utile.py", line 108, in check
    code = self.updateonline(fid)
  File "/code/./app/plugins/a4gtv/utile.py", line 66, in updateonline
    exit(-1)
  File "/usr/local/lib/python3.9/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: -1
[1mINFO    [0m  [32m2022-12-05 13:50:50.565[0m - [36msentry_sdk.integrations.logging[0m:[36msentry_patched_callhandlers[0m - [1m5.180.44.141:39098 - "GET /channel.m3u8?fid=4gtv-live050 HTTP/1.1" 500[0m
[32m[1mSUCCESS [0m  [32m2022-12-05 13:50:54.822[0m - [36mapp.plugins.a4gtv.endecrypt[0m:[36mget4gtvurl[0m - [32m[1m4gtv-4gtv017 216[0m
[31m[1mERROR   [0m  [32m2022-12-05 13:50:54.823[0m - [36mapp.plugins.a4gtv.utile[0m:[36mupdateonline[0m - [31m[1m该ip已被程序拉黑，无法访问[0m
[31m[1mERROR   [0m  [32m2022-12-05 13:50:54.824[0m - [36mapp.plugins.a4gtv.utile[0m:[36mupdateonline[0m - [31m[1m了解封禁规则https://github.com/239144498/Streaming-Media-Server-Pro/issues/14[0m
[31mERROR[0m:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/starlette.py", line 325, in _sentry_patched_asgi_app
    return await middleware(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/asgi.py", line 139, in _run_asgi3
    return await self._run_app(scope, lambda: self.app(scope, receive, send))
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/asgi.py", line 183, in _run_app
    return await callback()
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/starlette.py", line 130, in _create_span_call
    return await old_call(app, scope, new_receive, new_send, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/starlette.py", line 223, in _sentry_exceptionmiddleware_call
    await old_call(self, scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/starlette.py", line 130, in _create_span_call
    return await old_call(app, scope, new_receive, new_send, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/starlette.py", line 130, in _create_span_call
    return await old_call(app, scope, new_receive, new_send, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/fastapi.py", line 107, in _sentry_app
    return await old_app(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "/code/./app/api/v2/endpoints/sgtv.py", line 67, in channel1
    code = get.check(fid)  # 檢查是否出错

**Comment by charles0568** [comment]
INFO:     192.168.1.1:47242 - "GET /channel.m3u8?fid=4gtv-live205&hd=1080 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\sentry_sdk\integrations\starlette.py", line 325, in _sentry_patched_asgi_app
    return await middleware(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\sentry_sdk\integrations\asgi.py", line 139, in _run_asgi3
    return await self._run_app(scope, lambda: self.app(scope, receive, send))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\sentry_sdk\integrations\asgi.py", line 188, in _run_app
    raise exc from None
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\sentry_sdk\integrations\asgi.py", line 183, in _run_app
    return await callback()
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\sentry_sdk\integrations\starlette.py", line 130, in _create_span_call
    return await old_call(app, scope, new_receive, new_send, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\sentry_sdk\integrations\starlette.py", line 223, in _sentry_exceptionmiddleware_call
    await old_call(self, scope, receive, send)
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\sentry_sdk\integrations\starlette.py", line 130, in _create_span_call
    return await old_call(app, scope, new_receive, new_send, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\sentry_sdk\integrations\starlette.py", line 130, in _create_span_call
    return await old_call(app, scope, new_receive, new_send, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\sentry_sdk\integrations\fastapi.py", line 106, in _sentry_app
    return await old_app(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 235, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\temp\Streaming-Media-Server-Pro\app\api\v2\endpoints\sgtv.py", line 67, in channel1
    code = get.check(fid)  # 檢查是否出错
           ^^^^^^^^^^^^^^
  File "C:\temp\Streaming-Media-Server-Pro\app\plugins\a4gtv\utile.py", line 108, in check
    code = self.updateonline(fid)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\temp\Streaming-Media-Server-Pro\app\plugins\a4gtv\utile.py", line 47, in updateonline
    status_code, a6, a12, a1, msg = get4gtvurl(fid)
                                    ^^^^^^^^^^^^^^^
  File "C:\temp\Streaming-Media-Server-Pro\app\plugins\a4gtv\endecrypt.py", line 24, in get4gtvurl
    with request.post(url=url, headers=header, data=data, allow_redirects=True) as res:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\temp\Streaming-Media-Server-Pro\app\common\request.py", line 39, in post
    return self.request.post(url, data=data, json=json, headers=headers, proxies=self.proxies, timeout=10, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.naihe.me', port=443): Read timed out. (read timeout=10)

有許多頻道都已無法使用 怎麼會時常有這様的問題？？有些可以 有些不可以解析成功。。。可否解惑？

**Comment by kfcx** [comment]
服务在维护中，不过现在已经恢复正常，你的ip解除黑名单

**Comment by charles0568** [comment]
原來是在維護～感謝你~辛苦了～

**Comment by charles0568** [comment]
我的VPS 45.76.X.X 用DOCKER架的就還是不能使用 是否還是在黑名單中
[1mINFO    [0m  [32m2022-12-06 01:02:54.583[0m - [36msentry_sdk.integrations.logging[0m:[36msentry_patched_callhandlers[0m - [1m5.180.44.141:50738 - "GET /live/pool/4gtv-4gtv070/4gtv-live-mid/4gtv-4gtv070-avc1_2000000%3D1-mp4a_119000_zho%3D6-begin%3D2501883658053334-dur%3D40000000-seq%3D62547089.ts?token=CXDBFhXhupvzsLDyG4nDgQ&expires=1670259408&token1=oMMnIlPnbbs__xf2t3aHZg&expires1=1670259408&refer=NDcyNzExYTctZTU1Mi00OGIyLTkwNjItNmM2OGJlODU1OGM0&y=0 HTTP/1.1" 200[0m
[32m[1mSUCCESS [0m  [32m2022-12-06 01:02:54.587[0m - [36mapp.plugins.a4gtv.utile[0m:[36mgeneratem3u8[0m - [32m[1m4gtv-4gtv011 m3u8 generated successfully[0m
[1mINFO    [0m  [32m2022-12-06 01:02:54.588[0m - [36msentry_sdk.integrations.logging[0m:[36msentry_patched_callhandlers[0m - [1m23.175.146.234:50630 - "GET /channel.m3u8?fid=4gtv-4gtv011 HTTP/1.1" 200[0m
[32m[1mSUCCESS [0m  [32m2022-12-06 01:02:54.592[0m - [36mapp.plugins.a4gtv.utile[0m:[36mgeneratem3u8[0m - [32m[1m4gtv-4gtv070 m3u8 generated successfully[0m
[1mINFO    [0m  [32m2022-12-06 01:02:54.593[0m - [36msentry_sdk.integrations.logging[0m:[36msentry_patched_callhandlers[0m - [1m5.180.44.141:50916 - "GET /channel.m3u8?fid=4gtv-4gtv070 HTTP/1.1" 200[0m
[32m[1mSUCCESS [0m  [32m2022-12-06 01:02:54.597[0m - [36mapp.plugins.a4gtv.utile[0m:[36mgeneratem3u8[0m - [32m[1m4gtv-live050 m3u8 generated successfully[0m
[1mINFO    [0m  [32m2022-12-06 01:02:54.597[0m - [36msentry_sdk.integrations.logging[0m:[36msentry_patched_callhandlers[0m - [1m5.180.44.141:50960 - "GET /channel.m3u8?fid=4gtv-live050 HTTP/1.1" 200[0m
[1mINFO    [0m  [32m2022-12-06 01:03:04.636[0m - [36msentry_sdk.integrations.logging[0m:[36msentry_patched_callhandlers[0m - [1m23.175.146.234:50646 - "GET /channel.m3u8?fid=4gtv-live155 HTTP/1.1" 500[0m
[31mERROR[0m:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/starlette.py", line 325, in _sentry_patched_asgi_app
    return await middleware(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/asgi.py", line 139, in _run_asgi3
    return await self._run_app(scope, lambda: self.app(scope, receive, send))
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/asgi.py", line 188, in _run_app
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/asgi.py", line 183, in _run_app
    return await callback()
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/starlette.py", line 130, in _create_span_call
    return await old_call(app, scope, new_receive, new_send, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/starlette.py", line 223, in _sentry_exceptionmiddleware_call
    await old_call(self, scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/starlette.py", line 130, in _create_span_call
    return await old_call(app, scope, new_receive, new_send, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/starlette.py", line 130, in _create_span_call
    return await old_call(app, scope, new_receive, new_send, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/fastapi.py", line 107, in _sentry_app
    return await old_app(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "/code/./app/api/v2/endpoints/sgtv.py", line 67, in channel1
    code = get.check(fid)  # 檢查是否出错
  File "/code/./app/plugins/a4gtv/utile.py", line 108, in check
    code = self.updateonline(fid)
  File "/code/./app/plugins/a4gtv/utile.py", line 47, in updateonline
    status_code, a6, a12, a1, msg = get4gtvurl(fid)
  File "/code/./app/plugins/a4gtv/endecrypt.py", line 24, in get4gtvurl
    with request.post(url=url, headers=header, data=data, allow_redirects=True) as res:
  File "/code/./app/common/request.py", line 39, in post
    return self.request.post(url, data=data, json=json, headers=headers, proxies=self.proxies, timeout=10, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.naihe.me', port=443): Read timed out. (read timeout=10)
[1mINFO    [0m  [32m2022-12-06 01:03:14.708[0m - [36msentry_sdk.integrations.logging[0m:[36msentry_patched_callhandlers[0m - [1m23.175.146.234:50652 - "GET /channel.m3u8?fid=4gtv-live069 HTTP/1.1" 500[0m
[31mERROR[0m:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/starlette.py", line 325, in _sentry_patched_asgi_app
    return await middleware(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/asgi.py", line 139, in _run_asgi3
    return await self._run_app(scope, lambda: self.app(scope, receive, send))
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/asgi.py", line 188, in _run_app
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/asgi.py", line 183, in _run_app
    return await callback()
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/starlette.py", line 130, in _create_span_call
    return await old_call(app, scope, new_receive, new_send, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__

**Comment by kfcx** [comment]
该ip不在黑名单中，可以重启服务试试
