### ISSUE TITLE
运行后出错  改怎么配置哪些地方 

### ISSUE THREAD

**Issue by linlsyf** [239144498/Streaming-Media-Server-Pro#4]
Traceback (most recent call last):
  File "C:\Python\lib\site-packages\pymysql\connections.py", line 613, in connec
t
    sock = socket.create_connection(
  File "C:\Python\lib\socket.py", line 824, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Python\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Streaming-Media-Server-Pro-main\main.py", line 5, in <module>
    from app.main import app
  File "C:\Streaming-Media-Server-Pro-main\app\main.py", line 9, in <module>
    from app.utile import *
  File "C:\Streaming-Media-Server-Pro-main\app\utile.py", line 9, in <module>
    from app.tools import *
  File "C:\Streaming-Media-Server-Pro-main\app\tools.py", line 15, in <module>
    from app.settings import *
  File "C:\Streaming-Media-Server-Pro-main\app\settings.py", line 19, in <module
>
    mysql = get_a_conn()
  File "C:\Streaming-Media-Server-Pro-main\app\DBtools.py", line 125, in get_a_c
onn
    return MySQLConnect(cursorclass, MYSQL_config)
  File "C:\Streaming-Media-Server-Pro-main\app\DBtools.py", line 15, in __init__

    self.connection = pymysql.connect(
  File "C:\Python\lib\site-packages\pymysql\connections.py", line 353, in __init
__
    self.connect()
  File "C:\Python\lib\site-packages\pymysql\connections.py", line 664, in connec
t
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'xxx' ([E
rrno 11001] getaddrinfo failed)")

C:\Streaming-Media-Server-Pro-main>

**Comment by linlsyf** [comment]
看到了

**Comment by kfcx** [comment]
详细使用教程今天发布
