### ISSUE TITLE
导出program.m3u错误

### ISSUE THREAD

**Issue by zyjia** [239144498/Streaming-Media-Server-Pro#44]
使用的是最新版2.6
使用docker方式导出报网络错误
2023-01-05 15:22:50.719 | INFO     | app.conf.config:<module>:67 - 配置加载中...
....
2023-01-05 15:22:50.723 | WARNING  | app.conf.config:<module>:135 - 当前版本为2.6，最新版本为None，请及时更新！
2023-01-05 15:22:50.723 | WARNING  | app.conf.config:<module>:136 - 更新地址：https://github.com/239144498/Streaming-Media-Server-Pro
2023-01-05 15:22:50.724 | INFO     | app.conf.config:<module>:141 - 配置加载完成
2023-01-05 15:22:51.415 | INFO     | app.db.DBtools:<module>:15 - 正在检测数据库连接状态...
2023-01-05 15:22:51.417 | SUCCESS  | app.db.DBtools:connect_redis:30 - redis已连接
2023-01-05 15:22:51.490 | INFO     | app.db.dbMysql:init_database:85 - video表已存在
2023-01-05 15:22:51.491 | SUCCESS  | app.db.DBtools:<module>:57 - mysql已创建初始化表
None
2023-01-05 15:22:51.510 | SUCCESS  | app.db.DBtools:mysql_connect_test:44 - mysql已连接
2023-01-05 15:22:51.512 | SUCCESS  | app.plugins.a4gtv.utile:init:42 - init final
DEBUG     2023-01-05 15:22:51.619 - app.api:init_app - 日志系统已加载
INFO:     Started server process [1259336]
INFO      2023-01-05 15:22:51.697 - sentry_sdk.integrations.logging:sentry_patched_callhandlers - Started server process [1259336]
INFO:     Waiting for application startup.
INFO      2023-01-05 15:22:51.698 - sentry_sdk.integrations.logging:sentry_patched_callhandlers - Waiting for application startup.
INFO      2023-01-05 15:22:51.784 - app.api:startup - 已开启定时任务
/usr/local/lib/python3.10/dist-packages/apscheduler/util.py:436: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return tzinfo.localize(dt)
INFO:     Application startup complete.
INFO      2023-01-05 15:22:51.787 - sentry_sdk.integrations.logging:sentry_patched_callhandlers - Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8081 (Press CTRL+C to quit)
INFO      2023-01-05 15:22:51.788 - sentry_sdk.integrations.logging:sentry_patched_callhandlers - Uvicorn running on http://0.0.0.0:8081 (Press CTRL+C to quit)
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/sentry_sdk/integrations/starlette.py", line 325, in _sentry_patched_asgi_app
    return await middleware(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/sentry_sdk/integrations/asgi.py", line 139, in _run_asgi3
    return await self._run_app(scope, lambda: self.app(scope, receive, send))
  File "/usr/local/lib/python3.10/dist-packages/sentry_sdk/integrations/asgi.py", line 188, in _run_app
    raise exc from None
  File "/usr/local/lib/python3.10/dist-packages/sentry_sdk/integrations/asgi.py", line 183, in _run_app
    return await callback()
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/sentry_sdk/integrations/starlette.py", line 130, in _create_span_call
    return await old_call(app, scope, new_receive, new_send, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/dist-packages/sentry_sdk/integrations/starlette.py", line 223, in _sentry_exceptionmiddleware_call
    await old_call(self, scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/sentry_sdk/integrations/starlette.py", line 130, in _create_span_call
    return await old_call(app, scope, new_receive, new_send, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/sentry_sdk/integrations/starlette.py", line 130, in _create_span_call
    return await old_call(app, scope, new_receive, new_send, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 266, in __call__
    async with anyio.create_task_group() as task_group:
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 269, in wrap
    await func()
  File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 258, in stream_response
    async for chunk in self.body_iterator:
  File "/usr/local/lib/python3.10/dist-packages/starlette/concurrency.py", line 63, in iterate_in_threadpool
    yield await anyio.to_thread.run_sync(_next, iterator)
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/starlette/concurrency.py", line 53, in _next
    return next(iterator)
  File "/home/ubuntu/Streaming-Media-Server-Pro/app/plugins/a4gtv/tools.py", line 21, in generate_m3u
    for i in gdata:

TypeError: 'NoneType' object is not iterable
ERROR     2023-01-05 15:23:38.715 - sentry_sdk.integrations.logging:sentry_patched_callhandlers - Exception in ASGI application
Traceback (most recent call last):

  File "/home/ubuntu/Streaming-Media-Server-Pro/main.py", line 12, in <module>
    uvicorn.run(app=app, host="0.0.0.0", port=PORT, log_level="info")
    │       │       │                         └ 8081
    │       │       └ <fastapi.applications.FastAPI object at 0x7fc3716efca0>
    │       └ <function run at 0x7fc371635fc0>
    └ <module 'uvicorn' from '/usr/local/lib/python3.10/dist-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.10/dist-packages/uvicorn/main.py", line 576, in run
    server.run()
    │      └ <function Server.run at 0x7fc371697910>
    └ <uvicorn.server.Server object at 0x7fc36c44efb0>
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7fc3716979a0>
           │       │   └ <uvicorn.server.Server object at 0x7fc36c44efb0>
           │       └ <function run at 0x7fc372268280>
           └ <module 'asyncio' from '/usr/lib/python3.10/asyncio/__init__.py'>
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7fc36c5f6a40>
           │    └ <function BaseEventLoop.run_until_complete at 0x7fc3719f8a60>
           └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.10/asyncio/base_events.py", line 633, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7fc3719f89d0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7fc3719fa4d0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1896, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7fc371b51f30>
    └ <Handle Task.task_wakeup(<Future cancelled>)>
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future cancelled>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future cancelled>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future cancelled>)>
> File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
                   └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x7fc36c44f910>
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
                 │    │   │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7fc370371060>>
                 │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7fc370371060>>
                 │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('10.0.0.122', 8081), 'c...
                 │    └ <fastapi.applications.FastAPI object at 0x7fc3716efca0>
                 └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x7fc36c44f910>
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7fc370371060>>
                           │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7fc370371060>>
                           └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('10.0.0.122', 8081), 'c...
  File "/usr/local/lib/python3.10/dist-packages/sentry_sdk/integrations/starlette.py", line 325, in _sentry_patched_asgi_app
    return await middleware(scope, receive, send)
                 │          │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7fc370371060>>
                 │          │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7fc370371060>>
                 │          └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('10.0.0.122', 8081), 'c...
                 └ <sentry_sdk.integrations.asgi.SentryAsgiMiddleware object at 0x7fc37037d280>
  File "/usr/local/lib/python3.10/dist-packages/sentry_sdk/integrations/asgi.py", line 139, in _run_asgi3
    return await self._run_app(scope, lambda: self.app(scope, receive, send))
                 │    │        │              │    │   │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7fc370371060>>
                 │    │        │              │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7fc370371060>>
                 │    │        │              │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('10.0.0.122', 8081), 'c...
                 │    │        │              │    └ <member 'app' of 'SentryAsgiMiddleware' objects>
                 │    │        │              └ <sentry_sdk.integrations.asgi.SentryAsgiMiddleware object at 0x7fc37037d280>
                 │    │        └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('10.0.0.122', 8081), 'c...
                 │    └ <function SentryAsgiMiddleware._run_app at 0x7fc36fbac160>
                 └ <sentry_sdk.integrations.asgi.SentryAsgiMiddleware object at 0x7fc37037d280>
  File "/usr/local/lib/python3.10/dist-packages/sentry_sdk/integrations/asgi.py", line 188, in _run_app
    raise exc from None
  File "/usr/local/lib/python3.10/dist-packages/sentry_sdk/integrations/asgi.py", line 183, in _run_app
    return await callback()
                 └ <function SentryAsgiMiddleware._run_asgi3.<locals>.<lambda> at 0x7fc37043fac0>
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7fc370371060>>
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7fc370371060>>
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('10.0.0.122', 8081), 'c...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7fc36c41da50>
          └ <fastapi.applications.FastAPI object at 0x7fc3716efca0>
  File "/usr/local/lib/python3.10/dist-packages/sentry_sdk/integrations/starlette.py", line 130, in _create_span_call
    return await old_call(app, scope, new_receive, new_send, **kwargs)
                 │        │    │      │            │           └ {}
                 │        │    │      │            └ <function _enable_span_for_middleware.<locals>._create_span_call.<locals>._sentry_send at 0x7fc37043e710>
                 │        │    │      └ <function _enable_span_for_middleware.<locals>._create_span_call.<locals>._sentry_receive at 0x7fc37043e7a0>
                 │        │    └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('10.0.0.122', 8081), 'c...
                 │        └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7fc36c41da50>
                 └ <function ServerErrorMiddleware.__call__ at 0x7fc370a641f0>
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x7fc37043e680>
          │    │   │      └ <function _enable_span_for_middleware.<locals>._create_span_call.<locals>._sentry_receive at 0x7fc37043e7a0>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('10.0.0.122', 8081), 'c...
          │    └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x7fc36c41da20>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7fc36c41da50>
  File "/usr/local/lib/python3.10/dist-packages/sentry_sdk/integrations/starlette.py", line 223, in _sentry_exceptionmiddleware_call
    await old_call(self, scope, receive, send)
          │        │     │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x7fc37043e680>
          │        │     │      └ <function _enable_span_for_middleware.<locals>._create_span_call.<locals>._sentry_receive at 0x7fc37043e7a0>
          │        │     └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('10.0.0.122', 8081), 'c...
          │        └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x7fc36c41da20>
          └ <function _enable_span_for_middleware.<locals>._create_span_call at 0x7fc36c5f3d90>
  File "/usr/local/lib/python3.10/dist-packages/sentry_sdk/integrations/starlette.py", line 130, in _create_span_call
    return await old_call(app, scope, new_receive, new_send, **kwargs)
                 │        │    │      │            │           └ {}
                 │        │    │      │            └ <function _enable_span_for_middleware.<locals>._create_span_call.<locals>._sentry_send at 0x7fc37043e560>
                 │        │    │      └ <function _enable_span_for_middleware.<locals>._create_span_call.<locals>._sentry_receive at 0x7fc37043e7a0>
                 │        │    └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('10.0.0.122', 8081), 'c...
                 │        └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x7fc36c41da20>
                 └ <function ExceptionMiddleware.__call__ at 0x7fc370a64820>
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7fc37043e4d0>
          │    │   │      └ <function _enable_span_for_middleware.<locals>._create_span_call.<locals>._sentry_receive at 0x7fc37043e7a0>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('10.0.0.122', 8081), 'c...
          │    └ <fastapi.middleware.asyncexitstack.AsyncExitStackMiddleware object at 0x7fc36c41d9c0>
          └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x7fc36c41da20>
  File "/usr/local/lib/python3.10/dist-packages/sentry_sdk/integrations/starlette.py", line 130, in _create_span_call
    return await old_call(app, scope, new_receive, new_send, **kwargs)
                 │        │    │      │            │           └ {}
                 │        │    │      │            └ <function _enable_span_for_middleware.<locals>._create_span_call.<locals>._sentry_send at 0x7fc37043e3b0>
                 │        │    │      └ <function _enable_span_for_middleware.<locals>._create_span_call.<locals>._sentry_receive at 0x7fc37043e7a0>
                 │        │    └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('10.0.0.122', 8081), 'c...
                 │        └ <fastapi.middleware.asyncexitstack.AsyncExitStackMiddleware object at 0x7fc36c41d9c0>
                 └ <function AsyncExitStackMiddleware.__call__ at 0x7fc370a2ae60>
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
          │    │   │      │        └ <function _enable_span_for_middleware.<locals>._create_span_call.<locals>._sentry_send at 0x7fc37043e3b0>
          │    │   │      └ <function _enable_span_for_middleware.<locals>._create_span_call.<locals>._sentry_receive at 0x7fc37043e7a0>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('10.0.0.122', 8081), 'c...
          │    └ <fastapi.routing.APIRouter object at 0x7fc371728250>
          └ <fastapi.middleware.asyncexitstack.AsyncExitStackMiddleware object at 0x7fc36c41d9c0>
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function _enable_span_for_middleware.<locals>._create_span_call.<locals>._sentry_send at 0x7fc37043e3b0>
          │     │      │      └ <function _enable_span_for_middleware.<locals>._create_span_call.<locals>._sentry_receive at 0x7fc37043e7a0>
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('10.0.0.122', 8081), 'c...
          │     └ <function Route.handle at 0x7fc370a284c0>
          └ APIRoute(path='/program.m3u', name='program', methods=['GET'])
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function _enable_span_for_middleware.<locals>._create_span_call.<locals>._sentry_send at 0x7fc37043e3b0>
          │    │   │      └ <function _enable_span_for_middleware.<locals>._create_span_call.<locals>._sentry_receive at 0x7fc37043e7a0>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('10.0.0.122', 8081), 'c...
          │    └ <function request_response.<locals>.app at 0x7fc36c42bbe0>
          └ APIRoute(path='/program.m3u', name='program', methods=['GET'])
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
          │        │      │        └ <function _enable_span_for_middleware.<locals>._create_span_call.<locals>._sentry_send at 0x7fc37043e3b0>
          │        │      └ <function _enable_span_for_middleware.<locals>._create_span_call.<locals>._sentry_receive at 0x7fc37043e7a0>
          │        └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('10.0.0.122', 8081), 'c...
          └ <starlette.responses.StreamingResponse object at 0x7fc3703717b0>
  File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 266, in __call__
    async with anyio.create_task_group() as task_group:
               │     │                      └ <anyio._backends._asyncio.TaskGroup object at 0x7fc370371630>
               │     └ <function create_task_group at 0x7fc370e04d30>
               └ <module 'anyio' from '/usr/local/lib/python3.10/dist-packages/anyio/__init__.py'>
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
          └ [TypeError("'NoneType' object is not iterable")]
  File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 269, in wrap
    await func()
          └ functools.partial(<bound method StreamingResponse.stream_response of <starlette.responses.StreamingResponse object at 0x7fc37...
  File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 258, in stream_response
    async for chunk in self.body_iterator:
              │        │    └ <async_generator object iterate_in_threadpool at 0x7fc3703741c0>
              │        └ <starlette.responses.StreamingResponse object at 0x7fc3703717b0>
              └ b'#EXTM3U x-tvg-url=""\n'
  File "/usr/local/lib/python3.10/dist-packages/starlette/concurrency.py", line 63, in iterate_in_threadpool
    yield await anyio.to_thread.run_sync(_next, iterator)
                │     │         │        │      └ <generator object generate_m3u at 0x7fc36c4ff7d0>
                │     │         │        └ <function _next at 0x7fc370e55000>
                │     │         └ <function run_sync at 0x7fc370dc0dc0>
                │     └ <module 'anyio.to_thread' from '/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py'>
                └ <module 'anyio' from '/usr/local/lib/python3.10/dist-packages/anyio/__init__.py'>
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
                 └ <function get_asynclib at 0x7fc370dc0700>
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
                 └ <Future finished exception=TypeError("'NoneType' object is not iterable")>
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
             │       │   │      └ (<generator object generate_m3u at 0x7fc36c4ff7d0>,)
             │       │   └ <function _next at 0x7fc370e55000>
             │       └ <method 'run' of '_contextvars.Context' objects>
             └ <_contextvars.Context object at 0x7fc3703d0780>
  File "/usr/local/lib/python3.10/dist-packages/starlette/concurrency.py", line 53, in _next
    return next(iterator)
                └ <generator object generate_m3u at 0x7fc36c4ff7d0>

  File "/home/ubuntu/Streaming-Media-Server-Pro/app/plugins/a4gtv/tools.py", line 21, in generate_m3u
    for i in gdata:
             └ None

TypeError: 'NoneType' object is not iterable

WARNING   2023-01-05 15:23:38.926 - sentry_sdk.integrations.logging:sentry_patched_callhandlers - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', '', 'wrong version number')])"))': /api/4504005849579520/store/
WARNING   2023-01-05 15:23:39.126 - sentry_sdk.integrations.logging:sentry_patched_callhandlers - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', '', 'wrong version number')])"))': /api/4504005849579520/store/
WARNING   2023-01-05 15:23:39.329 - sentry_sdk.integrations.logging:sentry_patched_callhandlers - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', '', 'wrong version number')])"))': /api/4504005849579520/store/
WARNING   2023-01-05 15:23:39.717 - sentry_sdk.integrations.logging:sentry_patched_callhandlers - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', '', 'wrong version number')])"))': /api/4504005849579520/envelope/
WARNING   2023-01-05 15:23:39.911 - sentry_sdk.integrations.logging:sentry_patched_callhandlers - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', '', 'wrong version number')])"))': /api/4504005849579520/envelope/
WARNING   2023-01-05 15:23:40.107 - sentry_sdk.integrations.logging:sentry_patched_callhandlers - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', '', 'wrong version number')])"))': /api/4504005849579520/envelope/

**Comment by kfcx** [comment]
该接口不再支持,代理功能可以正常使用
