### ISSUE TITLE
一直报这个错

### ISSUE THREAD

**Issue by lck1115** [239144498/Streaming-Media-Server-Pro#9]
"[1mGET /channel.m3u8?fid=4gtv-4gtv002&hd=720 HTTP/1.1[0m" [32m200 OK[0m
[31mERROR[0m:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 68, in app
    await response(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/responses.py", line 260, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "/usr/local/lib/python3.9/site-packages/starlette/responses.py", line 256, in wrap
    await func()
  File "/usr/local/lib/python3.9/site-packages/starlette/responses.py", line 245, in stream_response
    async for chunk in self.body_iterator:
  File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 63, in iterate_in_threadpool
    yield await anyio.to_thread.run_sync(_next, iterator)
  File "/usr/local/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 53, in _next
    return next(iterator)
  File "/code/./app/utile.py", line 133, in generatem3u8
    self.check(fid, hd)
  File "/code/./app/utile.py", line 104, in check
    self.updateonline(fid, hd)
  File "/code/./app/utile.py", line 68, in updateonline
    start, seq, gap = genftlive(url)
  File "/code/./app/common/tools.py", line 59, in genftlive
    seq = re.findall("#EXT-X-MEDIA-SEQUENCE:(\d+)\n", data).pop()
IndexError: pop from empty list

这是什么情况啊

**Comment by kfcx** [comment]
> “�[1mGET /channel.m3u8?fid=4gtv-4gtv002&hd=720 HTTP/1.1�[0m”�[32m200 OK�[0m �[31mERROR�[0m: ASGI 应用程序中的异常 回溯（最近一次通话最后）： 文件“/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py”，第 404 行，在 run_asgi 结果=等待应用程序（＃类型：忽略[func-returns-value] 文件“/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py”，第 78 行， **调用 ** 返回等待 self.app（范围，接收，发送） 文件“/usr/local/lib/python3.9/site-packages/fastapi/applications.py”，第 269 行， **调用 **等待超级（）。 **调用 **（范围、接收、发送） 中的文件“/usr/local/lib/python3.9/site-packages/starlette/applications.py”，第 124 行 **调用 ** 等待 self.middleware_stack（范围，接收，发送） 文件“/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py”，第 184 行， **调用 ** 提高 exc 中的文件“/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py”，第 162 行 **调用 ** 等待 self.app（范围，接收，_send） 文件“/usr/local/lib/python3.9/site-packages/starlette/exceptions.py”，第 93 行， **调用 ** 提高 exc 文件“/usr/local/lib/python3.9/site-packages/starlette/exceptions.py”，第 82 行， **调用 ** 等待self.app（范围，接收，发件人） 文件“/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py”，第 21 行， **调用 ** 提高e 文件“/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py”，第 18 行， **调用 ** 等待 self.app（范围，接收，发送） 文件“/usr/local/lib/python3.9/site-packages/starlette/routing.py”，第 670 行， **调用 ** 等待 route.handle（范围，接收，发送） 文件“/usr/local/lib/python3.9/site-packages/starlette/routing.py”，第 266 行，在句柄中 等待 self.app（范围，接收，发送） 应用程序中的文件“/usr/local/lib/python3.9/site-packages/starlette/routing.py”，第 68 行 等待响应（范围，接收，发送） 文件“/usr/local/lib/python3.9/site-packages/starlette/responses.py”，第 260 行， **调用 ** 等待包装（部分（self.listen_for_disconnect，接收）） 中的文件“/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py”，第 662 行 **aexit ** 引发异常[0] 文件“/usr/local/lib/python3.9/site-packages/starlette/responses.py”，第 256 行，打包 等待函数（） 文件“/usr/local/lib/python3.9/site-packages/starlette/responses.py”，第 245 行，在 stream_response self.body_iterator 中块的异步： 文件“/usr/local/lib/python3.9/site-packages/starlette/concurrency.py”，第 63 行，在 iterate_in_threadpool yield await anyio.to_thread.run_sync(_next, iterator) 文件“/usr/local/lib/python3.9/site-packages/anyio/to_thread.py”，第 31 行，在 run_sync 返回等待 get_asynclib().run_sync_in_worker_thread( 文件“/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py”，第 937 行，在 run_sync_in_worker_thread 返回等待未来 运行中的文件“/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py”，第 867 行 结果 = context.run(func, *args) _next 中的文件“/usr/local/lib/python3.9/site-packages/starlette/concurrency.py”，第 53 行 返回下一个（迭代器） 文件“/code/./app/utile.py”，第 133 行，在 generatem3u8 中 自我检查（fid，高清） 检查文件“/code/./app/utile.py”，第 104 行 self.updateonline(fid, hd) 文件“/code/./app/utile.py”，第 68 行，在 updateonline 开始，序列，间隙 = genftlive(url) 文件“/code/./app/common/tools.py”，第 59 行，在 genftlive seq = re.findall("#EXT-X-MEDIA-SEQUENCE:(\d+)\n", data).pop() IndexError：从空列表中弹出
> 
> 这是什么情况啊

自从我开放接口以来发现有恶意人员故意刷接口流量，每天的恶意请求数量达到几十万条，外出流量达数TB流量，所以对接口采取了限制，你可以使用/channel2.m3u8接口，正常使用没问题。

**Comment by lck1115** [comment]
我这是部署在自己服务器上的啊。。

而且用channel2也是提示这个错误。。

**Comment by Jack-733** [comment]
一样的错误，昨晚在群晖中搭好没问题，今天就不能看了。
